services:
  bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    environment:
      DB_HOST: dual_db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
    networks:
      - discord_bot

networks:
  discord_bot:
    external: true
